const fs = require('fs');
const path = require('path');

function createPlace(name, city, lat, lng, cat, feeI, feeF, best, desc, hist, cult, arch, facts) {
  return {
    destination_name: name,
    city: city,
    state: "Karnataka",
    country: "India",
    latitude: lat,
    longitude: lng,
    description: desc,
    detailedInfo: {
        history: hist,
        cultural_significance: cult,
        architecture: arch,
        interesting_facts: facts
    },
    images: [], // To be populated by downloader
    entry_fee: {
        indian: feeI,
        foreign: feeF || feeI
    },
    best_time_to_visit: best,
    category: cat
  };
}

const places = [
  createPlace('Hampi', 'Hampi', 15.3350, 76.4600, 'Heritage', '₹40', '₹600', 'Oct-Mar', 'A UNESCO World Heritage site known for ancient ruins of the Vijayanagara Empire.', 'Capital of the Vijayanagara Empire (14th century), it was one of the richest cities in the world.', 'Symbolizes the pinnacle of South Indian power and culture.', 'Dravidian style with massive stone chariots, pillars, and courtyards.', 'It was the second largest medieval-era city after Beijing.'),
  createPlace('Mysore Palace', 'Mysore', 12.3051, 76.6551, 'Heritage', '₹70', '₹200', 'Oct-Mar', 'A historical palace and royal residence at Mysore, illuminated brightly on Sundays.', 'Built for the Wadiyar dynasty who ruled the Kingdom of Mysore from 1399 to 1950.', 'Center of the famous Mysuru Dasara festival celebrating triumph of good over evil.', 'Indo-Saracenic style blending Hindu, Mughal, Rajput, and Gothic architecture.', 'It is the second most visited historical monument in India after the Taj Mahal.'),
  createPlace('Gol Gumbaz', 'Bijapur', 16.8291, 75.7366, 'Heritage', '₹25', '₹300', 'Oct-Feb', 'The mausoleum of Mohammed Adil Shah, notable for its massive dome and whispering gallery.', 'Constructed in 1656 by the Adil Shahi Dynasty.', 'A masterclass of Deccan Sultanate architectural grandeur.', 'Features the second largest dome in the world without pillar support.', 'A whisper at one side of the whispering gallery can be heard clearly on the other side.'),
  createPlace('Pattadakal', 'Pattadakal', 15.9497, 75.8160, 'Heritage', '₹40', '₹600', 'Oct-Mar', 'A UNESCO site showcasing Badami Chalukya architecture.', 'Built in the 7th and 8th centuries by the Chalukya dynasty.', 'Represents a harmonious blend of architectural forms from northern and southern India.', 'Vesara style temples integrating Nagara and Dravidian forms.', 'Used as the royal coronation site for the Chalukya kings.'),
  createPlace('Aihole', 'Aihole', 16.0182, 75.8797, 'Heritage', '₹25', '₹300', 'Oct-Mar', 'A historic site known as the "cradle of Hindu rock architecture".', 'Served as an early capital of the Chalukyas before Badami.', 'Contains over 120 stone and cave temples from various faiths.', 'Features early experimental structures of temple building.', 'The Durga Temple has an unusual apsidal (semi-circular) plan.'),
  createPlace('Bidar Fort', 'Bidar', 17.9221, 77.5312, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'A massive medieval fort known for its Persian architecture and water management systems.', 'Expanded by Ahmad Shah I Wali of the Bahmani Sultanate in 1427.', 'A significant cultural hub integrating Persian, Turkish, and Deccan styles.', 'Features distinctive Karez water supply system and Rangin Mahal.', 'Contains one of the most robust ancient cannon armories in India.'),
  createPlace('Chitradurga Fort', 'Chitradurga', 14.2173, 76.3957, 'Heritage', '₹25', '₹300', 'Sep-Feb', 'A massive hill fort known for its multi-layered defensive walls.', 'Built and expanded between the 11th and 18th centuries by various dynasties including the Nayakas.', 'Famous for the legend of Onake Obavva, a brave woman who fought Haider Ali\'s soldiers.', 'Features 19 gateways, 38 posterior entrances, and 35 secret entrances.', 'Never faced a shortage of water due to numerous interconnected reservoirs.'),
  createPlace('Tipu Sultan Summer Palace', 'Bangalore', 12.9615, 77.5739, 'Heritage', '₹20', '₹200', 'Year Round', 'An exquisite example of Indo-Islamic architecture built primarily of teak.', 'Completed in 1791, it was the summer residence of the Mysorean ruler Tipu Sultan.', 'Reflects the opulent lifestyle and artistic taste of Tipu Sultan.', 'Ornate teak pillars, arches, and balconies adorned with floral motifs.', 'Houses a museum detailing Tipu Sultan’s reign and his rockets.'),
  createPlace('Bangalore Palace', 'Bangalore', 12.9988, 77.5921, 'Heritage', '₹230', '₹460', 'Year Round', 'A royal palace known for its Tudor-style architecture resembling Windsor Castle.', 'Built in 1878 by Rev. J. Garrett, later bought by the Wadiyars.', 'Hosts numerous cultural events, concerts, and exhibitions.', 'Features fortified towers, Gothic windows, and elegant wood carvings.', 'The palace grounds have hosted concerts by Iron Maiden and Metallica.'),
  createPlace('Srirangapatna', 'Mandya', 12.4237, 76.6826, 'Heritage', '₹20', '₹200', 'Oct-Mar', 'An island town holding deep historical, religious, and cultural significance.', 'Served as the capital of the warrior-kings Hyder Ali and Tipu Sultan.', 'A major pilgrimage center housing the Ranganathaswamy Temple.', 'Blends Hoysala and Vijayanagara temple architecture with Islamic palaces.', 'The town is entirely enclosed by the river Kaveri.'),
  createPlace('Shivagange', 'Tumkur', 13.1691, 77.2285, 'Spiritual', 'Free', 'Free', 'Sep-Feb', 'A mountain peak shaped like an open Shiva Linga with a spring flowing locally.', 'Known as Dakshina Kashi (Kashi of the South) with temples dating back centuries.', 'A major Hindu pilgrimage and trekking destination.', 'Steep rock carvings and ancient shrines nestled in the mountain.', 'From different angles, the hill resembles a Nandi, Ganesha, Linga, and Cobra.'),
  createPlace('Kittur Fort', 'Kittur', 15.6027, 74.7936, 'Heritage', '₹20', '₹200', 'Oct-Feb', 'A historical fort associated with Rani Chennamma’s rebellion against the British.', 'Erected by the Desai dynasty, it witnessed the famous 1824 Kittur rebellion.', 'A symbol of early Indian resistance against British colonial rule.', 'Built from basalt rock, blending regional fortification styles.', 'Houses a museum with ancient weapons, inscriptions, and idols.'),
  createPlace('Coorg (Madikeri)', 'Madikeri', 12.4244, 75.7382, 'Hill Station', 'Free', 'Free', 'Sep-Mar', 'The "Scotland of India", famous for coffee plantations and lush landscapes.', 'Historically ruled by the Haleri kings before British annexation.', 'Home to the Kodava people, known for their distinct culture and martial traditions.', 'Features colonial-era bungalows and traditional Kodava ainmanes (ancestral homes).', 'Produces some of the world’s best robusta and arabica coffee.'),
  createPlace('Chikmagalur', 'Chikmagalur', 13.3153, 75.7754, 'Hill Station', 'Free', 'Free', 'Sep-Mar', 'The birthplace of coffee in India, surrounded by the Mullayanagiri range.', 'Coffee was first introduced here by Baba Budan in the 17th century.', 'A prominent hub for eco-tourism and coffee heritage.', 'Dotted with heritage homestays and estate architecture.', 'The name translates to "Younger Daughter\'s Town" in Kannada.'),
  createPlace('Nandi Hills', 'Chikkaballapur', 13.3702, 77.6835, 'Nature', '₹20', '₹20', 'Year Round', 'A scenic hill fortress known for spectacular sunrise views.', 'Used by Tipu Sultan as a summer retreat and fortress.', 'A massive tourist hotspot for Bangalore residents.', 'Features the ancient Bhoga Nandeeshwara Temple at the base.', 'Tipu\'s Drop is a sheer cliff face from which prisoners were allegedly cast.'),
  createPlace('Agumbe', 'Shimoga', 13.5042, 75.0954, 'Nature', 'Free', 'Free', 'Jun-Sep', 'Known as the "Cherrapunji of the South" due to heavy rainfall and rainforests.', 'Historically significant for forest conservation and herpetology.', 'Famous for the Agumbe Rainforest Research Station protecting King Cobras.', 'Traditional Malnad style village houses with sloping roofs.', 'The famous 1980s TV series "Malgudi Days" was filmed here.'),
  createPlace('Kudremukh', 'Chikmagalur', 13.2085, 75.2581, 'Nature', '₹200', '₹200', 'Oct-Feb', 'A mountain shaped like a horse\'s face, known for trekking and biodiversity.', 'Formerly an iron ore mining town, now a protected national park.', 'A vital ecological hotspot within the Western Ghats.', 'Natural rolling grasslands and dense Shola forests.', 'Mining here was stopped entirely to protect the sensitive ecosystem.'),
  createPlace('Sakleshpur', 'Hassan', 12.9702, 75.7865, 'Hill Station', 'Free', 'Free', 'Sep-Mar', 'A tranquil hill station adorned with coffee estates and spice plantations.', 'Historically under the Hoysalas, and later the Mysore kings.', 'Famous for the "Green Route" trek along the railway tracks.', 'Features the star-shaped Manjarabad Fort built by Tipu Sultan.', 'The region produces massive quantities of pepper and cardamom.'),
  createPlace('Kemmanagundi', 'Chikmagalur', 13.5487, 75.7562, 'Hill Station', 'Free', 'Free', 'Sep-Feb', 'A beautiful hill station with ornamental gardens and mountain streams.', 'Established as a summer retreat by Krishnaraja Wodeyar IV.', 'Renowned for its meticulously landscaped royal gardens (Z Point).', 'Lush botanical landscapes atop high ridges.', 'Donated by the king to the Government of Karnataka for public use.'),
  createPlace('Kodachadri', 'Shimoga', 13.8561, 74.8732, 'Adventure', 'Free', 'Free', 'Oct-Jan', 'A dense forest peak in the Western Ghats famous for challenging treks.', 'Associated with Adi Shankaracharya who is said to have meditated here.', 'A spiritual and adventure hotspot containing the Sarvajna Peetha.', 'A small stone temple sits at the very summit.', 'Designated as a natural heritage site by the Government of Karnataka.'),
  ...[
    // Auto expanding via an array of minimal records mapped into the createPlace function
    ['Baba Budangiri', 'Chikmagalur', 13.411, 75.759, 'Adventure', 'Free', 'Free', 'Sep-Mar', 'A mountain range famous for its Sufi shrine and hiking trails.', 'Named after the Sufi saint Baba Budan who smuggled coffee beans from Yemen.', 'Revered by both Hindus and Muslims as a site of harmony.', 'Natural caves and simple shrine architectures.', 'The region blooms with the rare Kurinji flower once every 12 years.'],
    ['Male Mahadeshwara Hills', 'Chamarajanagar', 12.046, 77.535, 'Spiritual', 'Free', 'Free', 'Oct-Mar', 'A renowned pilgrimage center surrounded by dense forests.', 'Dedicated to Lord Shiva, incarnated as Sri Male Mahadeshwara.', 'Attracts millions of devotees during specific jataras (fairs).', 'Massive temple complex nestled in hills.', 'The surrounding forests were once the territory of the bandit Veerappan.'],
    ['Anthargange', 'Kolar', 13.146, 78.106, 'Adventure', 'Free', 'Free', 'Sep-Feb', 'A massive field of volcanic boulders perfect for night trekking and cave exploration.', 'The Sri Kashi Vishweshwara temple here receives a continuous underground spring.', 'Known as the Kashi of the South due to its sacred water.', 'Natural cave formations and intricate stone temples.', 'The source of the continuous spring water remains a geological mystery.'],
    ['Devarayanadurga', 'Tumkur', 13.376, 77.109, 'Nature', 'Free', 'Free', 'Oct-Feb', 'A rocky hill station with old temples and stunning panoramic views.', 'It was originally fortified by a local chieftain and later captured by Mysore kings.', 'Famous for the Yoga Narasimha and Bhoga Narasimha temples.', 'Dravidian style temples at multiple altitudes on the hill.', 'Home to the Namada Chilume, a natural spring linked to Lord Rama.'],
    ['Shivanasamudra Falls', 'Mandya', 12.298, 77.170, 'Nature', 'Free', 'Free', 'Jul-Nov', 'Spectacular twin waterfalls on the Kaveri river.', 'Site of one of the first hydro-electric power stations in Asia (set up in 1902).', 'Powers historic towns, including the Kolar Gold Fields originally.', 'Natural cascading segmented waterfalls over rocky terrain.', 'The segmented falls are named Gaganachukki and Bharachukki.'],
    ['Hebbe Falls', 'Chikmagalur', 13.542, 75.733, 'Nature', '₹400', '₹400', 'Aug-Jan', 'A mesmerizing waterfall accessible via a thrilling jeep ride.', 'A prominent landmark in the Bhadra Tiger Reserve.', 'The water is believed to have medicinal properties infused with local herbs.', 'Two-tiered falls known as Dodda Hebbe and Chikka Hebbe.', 'Requires a 4x4 jeep safari due to the extremely rough terrain.'],
    ['Sathodi Falls', 'Yellapur', 14.938, 74.577, 'Nature', '₹20', '₹20', 'Sep-Jan', 'A picturesque rectangular waterfall deep inside the jungle.', 'Formed by several unnamed streams converging near Kallaramane Ghat.', 'A tranquil, less commercialized picnic spot.', 'Natural rock formations block the pool perfectly.', 'Often referred to as the "Mini Niagara of Uttara Kannada".'],
    ['Iruppu Falls', 'Kodagu', 11.950, 75.996, 'Nature', '₹50', '₹50', 'Aug-Jan', 'A stunning waterfall bordering the Brahmagiri Wildlife Sanctuary.', 'According to legend, Lakshmana shot an arrow into the hills to get drinking water.', 'A major pilgrimage spot during Shivaratri.', 'Cascades down a steep rocky facade in amidst dense jungle.', 'The stream is known as Lakshmana Tirtha and joins the Kaveri river.'],
    ['Gokak Falls', 'Belagavi', 16.195, 74.779, 'Nature', 'Free', 'Free', 'Jul-Oct', 'A massive waterfall on the Ghataprabha river, resembling Niagara Falls.', 'Features a historic suspension bridge across the gorge.', 'Fueled early industrialization with a cotton mill established in 1887.', 'Natural cliff drop with a historic hanging bridge.', 'The river drops 52 meters over a sandstone cliff.'],
    ['Magod Falls', 'Yellapur', 14.851, 74.733, 'Nature', '₹10', '₹10', 'Jul-Dec', 'A two-tiered waterfall where the Bedthi river plunges nearly 200m.', 'Nestled amidst dense, untouched evergreen forests.', 'A quiet, pristine nature retreat far from city life.', 'Natural forested gorge.', 'Situated on the way to the famous Jenukallu Gudda viewpoint.'],
    ['Kalhatti Falls', 'Chikmagalur', 13.565, 75.772, 'Nature', 'Free', 'Free', 'Jul-Nov', 'A beautiful waterfall cascading over the ancient Veerabhadreshwara Temple.', 'Legend says sage Agastya prayed here.', 'Combines natural beauty with historic religious pilgrimage.', 'A waterfall flowing directly over ancient rock-cut stone elephants.', 'Water drops from a height of 122 meters.'],
    ['Unchalli Falls', 'Sirsi', 14.423, 74.745, 'Nature', '₹10', '₹10', 'Jul-Jan', 'A majestic waterfall discovered by J.D. Lushington in 1845.', 'Also called Lushington Falls in honor of the British collector.', 'Known for its deafening roar, earning the local name "Keppa Joga".', 'Deep, dramatic plunge pool surrounded by dense forest.', 'Creates spectacular rainbows on sunny days due to intense mist.'],
    ['Gokarna', 'Gokarna', 14.539, 74.314, 'Beaches', 'Free', 'Free', 'Oct-Mar', 'A coastal temple town known for pristine beaches and relaxed vibes.', 'Historically a major Shaivite pilgrimage center containing the Atmalinga.', 'A unique blend of ancient religious traditions and modern backpacker culture.', 'Rustic beach shacks alongside ancient Dravidian temples.', 'Gokarna means "Cow\'s Ear" in Sanskrit, referring to the ear-shaped confluence of local rivers.'],
    ['Kudle Beach', 'Gokarna', 14.530, 74.309, 'Beaches', 'Free', 'Free', 'Oct-Mar', 'A long, beautiful crescent-shaped beach near Gokarna town.', 'A highly popular spot for backpackers and yogis.', 'Known for its peaceful, bohemian lifestyle and sunset views.', 'Lined with seasonal palm-thatched beach shacks.', 'It is inaccessible by major roads, requiring a short hike from the hill top.'],
    ['Half Moon Beach', 'Gokarna', 14.516, 74.321, 'Beaches', 'Free', 'Free', 'Oct-Mar', 'A secluded, tiny beach accessible only by boat or hiking.', 'Remains untouched by massive commercialization.', 'Perfect retreat for tranquility and raw coastal nature.', 'Raw sandy coves bounded by steep rocky cliffs.', 'There are no paved roads leading to this beach.'],
    ['Paradise Beach', 'Gokarna', 14.511, 74.326, 'Beaches', 'Free', 'Free', 'Oct-Feb', 'The ultimate secluded beach in Gokarna, perfect for camping.', 'Historically a hippie haven in the 1990s and 2000s.', 'A pristine, zero-infrastructure coastal experience.', 'Rocky outcrops mixing with white sands.', 'Virtually inaccessible during monsoon due to high tides.'],
    ['Karwar Beach', 'Karwar', 14.805, 74.129, 'Beaches', 'Free', 'Free', 'Oct-Feb', 'A pristine and calm beach famously praised by Rabindranath Tagore.', 'Historically an important port town for the British and Portuguese.', 'Tagore penned his first play here, inspired by the beach\'s beauty.', 'Wide sandy stretches with a warship museum (INS Chapal).', 'Features an authentic decommissioned Indian Navy missile boat on the beach.'],
    ['Malpe Beach', 'Udupi', 13.350, 74.699, 'Beaches', 'Free', 'Free', 'Oct-Feb', 'A vibrant beach famous for water sports and access to St. Mary\'s Island.', 'A major natural port and fishing harbor of the Karnataka coast.', 'A hub for maritime culture and shipbuilding.', 'Features a sea walk and bustling fishing docks.', 'It offers the first Free Wi-Fi beach experience in India.'],
    ['Kapu Beach', 'Udupi', 13.226, 74.738, 'Beaches', '₹10', '₹10', 'Oct-Feb', 'A stunning beach known for its historic 1901 lighthouse built on a rock.', 'The lighthouse was built by the British East India Company.', 'A vital navigational landmark for Arabian Sea sailors.', 'A 130-foot tall circular masonry lighthouse.', 'Visitors can climb the lighthouse for a breathtaking panoramic view of the sea.'],
    ['Maravanthe Beach', 'Kundapura', 13.712, 74.636, 'Beaches', 'Free', 'Free', 'Oct-Mar', 'A unique scenic spot where the highway runs exactly between the ocean and a river.', 'The Souparnika River flows parallel to the Arabian Sea.', 'A natural geographical marvel rarely seen elsewhere.', 'A narrow strip of tarmac separating turbulent seas from calm river waters.', 'The spot is incredibly dangerous but spectacular during heavy monsoons.'],
    ['Kabini', 'Mysore', 11.975, 76.257, 'Nature', '₹1000', '₹2000', 'Oct-May', 'A massive reservoir and wildlife hotspot famous for leopard and black panther sightings.', 'Once a private hunting lodge for the Maharaja of Mysore.', 'Now one of the premier wildlife photography destinations in Asia.', 'Extensive backwaters giving life to dense deciduous forests.', 'The local black panther "Saya" became a global sensation through documentaries.'],
    ['Dandeli Wildlife Sanctuary', 'Dandeli', 15.244, 74.622, 'Nature', '₹200', '₹200', 'Oct-May', 'A dense forest famous for white water rafting and the rare Black Panther.', 'A major timber producing hub during the colonial era.', 'A hotspot for adventure sports and bird watching (hornbecks).', 'Deciduous forests intersected by the raging Kali River.', 'Home to over 300 species of rare indigenous birds.'],
    ['Bannerghatta National Park', 'Bangalore', 12.800, 77.577, 'Nature', '₹280', '₹400', 'Year Round', 'A highly accessible biological park featuring a tiger and lion safari.', 'Established in 1970 and declared a national park in 1974.', 'Promotes wildlife conservation at the edge of a major metropolis.', 'Features a zoo, a pet corner, an animal rescue center, and a butterfly enclosure.', 'Houses India\'s first biological park butterfly enclosure.'],
    ['Bhadra Wildlife Sanctuary', 'Chikmagalur', 13.737, 75.626, 'Nature', '₹300', '₹300', 'Oct-May', 'A protected tiger reserve nestled in the misty Western Ghats.', 'Named after the Bhadra River which flows through it.', 'A biodiversity hotspot crucial for the survival of the Malabar giant squirrel.', 'Moist deciduous forests with immense teak and rosewood trees.', 'Rich in rare timber but strictly protected from logging.'],
    ['Kali Tiger Reserve', 'Dandeli', 15.105, 74.524, 'Nature', '₹250', '₹250', 'Oct-May', 'A massive tiger reserve encompassing deep valleys and the Kali River.', 'Formerly known as Anshi National Park, later rebranded.', 'Critical habitat for the elusive black panther and Bengal tiger.', 'Steep, challenging forest terrain with river valleys.', 'It remains one of the least disturbed wildlife habitats in Karnataka.'],
    ['Sharavathi Valley Wildlife Sanctuary', 'Shimoga', 14.120, 74.870, 'Nature', '₹200', '₹200', 'Oct-May', 'A beautiful forest encompassing the Sharavathi river basin and Jog Falls.', 'Created around the Linganamakki reservoir.', 'An ecological paradise for rare Lion-tailed Macaques.', 'Tropical evergreen forests and extensive lake backwaters.', 'Much of the sanctuary is only accessible by boat.'],
    ['Someshwara Wildlife Sanctuary', 'Udupi', 13.486, 75.037, 'Nature', '₹150', '₹150', 'Oct-May', 'A bio-diverse sanctuary at the foot of the Agumbe Ghats.', 'Named after the presiding deity Lord Someshwara.', 'Acts as a critical corridor for wildlife moving through the Western Ghats.', 'Dense evergreen and semi-evergreen forest landscape.', 'Receives some of the highest rainfall measurements in India.'],
    ['Cauvery Wildlife Sanctuary', 'Chamarajanagar', 12.049, 77.347, 'Nature', '₹200', '₹200', 'Nov-Mar', 'A protected area covering the riverine forests of the Kaveri river.', 'Historically the roaming grounds for ancient hunter-gatherers and later, poachers.', 'Crucial for the conservation of the highly endangered Mahseer fish.', 'Riverine tracts, gorges, and dry deciduous scrub forests.', 'Once the exclusive fishing ground for the British colonial officials.'],
    ['Udupi Krishna Temple', 'Udupi', 13.340, 74.748, 'Spiritual', 'Free', 'Free', 'Year Round', 'A famous Hindu temple dedicated to Lord Krishna and founded in the 13th century.', 'Founded by the great Vaishnavite saint Shri Madhvacharya in the 13th century.', 'A major hub of the Dvaita philosophy and classical Udupi cuisine.', 'Legend says the Krishna idol turned around to give darshan through a window to Kanakadasa.', 'The deity is uniquely worshipped through a silver-plated window (Kanakana Kindi).'],
    ['Dharmasthala', 'Dakshina Kannada', 9.948, 75.385, 'Spiritual', 'Free', 'Free', 'Year Round', 'A unique temple town where a Jain Bunt family administers a Hindu temple.', 'The temple is dedicated to Lord Shiva, but the priests are Vaishnavite Brahmins.', 'A massive symbol of religious tolerance and charity (Annadana).', 'Features a massive monolithic statue of Bahubali.', 'Provides free food and subsidized accommodation to over 10,000 pilgrims daily.'],
    ['Kollur Mookambika Temple', 'Udupi', 13.864, 74.814, 'Spiritual', 'Free', 'Free', 'Year Round', 'A powerful Shakti temple located in the foothills of the Kodachadri peak.', 'Consecrated by Adi Shankaracharya according to Hindu legend.', 'Patronized by the kings of the Keladi Nayaka dynasty.', 'Traditional Kerala-style architecture with a gold-plated crest.', 'A very important pilgrimage site for classical musicians and scholars.'],
    ['Sringeri', 'Chikmagalur', 13.420, 75.257, 'Spiritual', 'Free', 'Free', 'Year Round', 'The first matha established by Adi Shankaracharya on the banks of the Tunga River.', 'Established in the 8th century to propagate Advaita Vedanta philosophy.', 'A premier center for Vedic learning and philosophy in India.', 'The Vidyashankara temple here incorporates twelve pillars representing the zodiac.', 'The river here runs thick with sacred fish that pilgrims feed by hand.'],
    ['Gokarna Mahabaleshwar Temple', 'Gokarna', 14.542, 74.318, 'Spiritual', 'Free', 'Free', 'Year Round', 'A 4th-century CE Hindu temple housing the sacred Atmalinga.', 'Mentioned in the epic Mahabharata and Ramayana.', 'Considered as sacred as Kashi for undertaking final rites.', 'Classic Dravidian architecture crafted from granite.', 'The deity can only be viewed through a small hole in a stone slab.'],
    ['Chamundeshwari Temple', 'Mysore', 12.270, 76.670, 'Spiritual', 'Free', 'Free', 'Year Round', 'Perched on Chamundi Hills, dedicated to the fierce form of Durga.', 'The deity is the tutelary goddess of the Mysore Maharajas.', 'A defining icon of Mysore\'s religious and cultural identity.', 'Features a 1000-step ancient stairway and a massive Nandi statue.', 'The temple dates back to the 12th century Hoysala period.'],
    ['Kukke Subramanya', 'Dakshina Kannada', 12.662, 75.617, 'Spiritual', 'Free', 'Free', 'Year Round', 'A sacred temple dedicated to Lord Kartikeya, worshipped as the lord of serpents.', 'Believed to be the place where the snake king Vasuki sought refuge.', 'Famous for rites related to Sarpa Dosha (serpent curses).', 'Surrounded by the steep Kumara Parvatha mountain ranges.', 'The temple is built facing east, but pilgrims enter through the western rear gate.'],
    ['Melukote', 'Mandya', 12.660, 76.647, 'Spiritual', 'Free', 'Free', 'Year Round', 'A historic temple town known for the Cheluvanarayana Swamy Temple.', 'The great Vaishnava saint Ramanujacharya lived here for 12 years in the 12th century.', 'A prominent hub of Sri Vaishnava culture, literature, and silk weaving.', 'Features large temple ponds (Kalyanis) and monolithic pillars.', 'The Vairamudi festival here attracts hundreds of thousands of devotees.'],
    ['Horanadu Annapoorneshwari', 'Chikmagalur', 13.272, 75.340, 'Spiritual', 'Free', 'Free', 'Year Round', 'A temple dedicated to the Goddess of Food, nestled in thick forests.', 'Established by sage Agastya in ancient times.', 'Upholds the tradition that no visitor leaves hungry regardless of religion.', 'Refurbished significantly in the 20th century using local granite.', 'The main deity is made entirely of gold.'],
    ['Bangalore', 'Bangalore', 12.971, 77.594, 'Heritage', 'Free', 'Free', 'Year Round', 'The capital city, known as the IT hub and the Garden City of India.', 'Founded by Kempe Gowda I in 1537 as a mud fort.', 'A cultural melting pot integrating technology, arts, and vibrant nightlife.', 'Modern skyscrapers juxtaposed with colonial-era public buildings and parks.', 'It features Cubbon Park, a 300-acre green oasis in the heart of the city.'],
    ['Mysore', 'Mysore', 12.295, 76.639, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'The cultural capital of Karnataka, famous for its palaces and Dasara festival.', 'The stronghold of the Wadiyar dynasty who patronized art and culture globally.', 'Globally famous for its premium silk, sandalwood, and unique painting styles.', 'Characterized by heavily ornate Indo-Saracenic royal buildings.', 'Recognized as the birthplace of Ashtanga Yoga.'],
    ['Mangalore', 'Mangalore', 12.914, 74.856, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'A major port city known for its diverse culture and amazing coastal cuisine.', 'A vital trading port since the 6th century, contested by multiple empires.', 'Famed for its unique Tulu culture, Yakshagana, and spicy seafood.', 'Features red-tiled roofed buildings and striking Catholic churches.', 'Named after the local Hindu deity Mangaladevi.'],
    ['Hubli', 'Hubli', 15.364, 75.124, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'A commercial hub and the second largest city in Karnataka, famous for the Sufi shrine.', 'Known as "Eleya Puravada Halli" (Village of tender creepers) historically.', 'A major center for Hindustani classical music in southern India.', 'Industrial layout paired with pre-independence classical structures.', 'Hubli has produced several legends of the Kirana gharana music style.'],
    ['Dharwad', 'Dharwad', 15.458, 75.007, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'A twin city to Hubli, known for its educational institutions and Pedha (sweet).', 'The name Dharwad means a place of rest in a long travel or a small habitation.', 'Considered the cultural and educational capital of North Karnataka.', 'Colonial educational infrastructure with extensive university campuses.', 'Dharwad pedha has a Geographical Indication (GI) tag.'],
    ['Belgaum', 'Belgaum', 15.849, 74.497, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'A border city featuring a massive fort and a pleasant climate year-round.', 'Founded in the late 12th century by the Ratta dynasty.', 'A cultural transition zone blending Marathi and Kannada influences.', 'Features the Belgaum Fort with its moats, Kamal Basti, and mosques.', 'Swami Vivekananda stayed here for nine days in 1892.'],
    ['Gulbarga', 'Gulbarga', 17.329, 76.834, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'Now called Kalaburagi, famous for its magnificent fort and Sufi shrines.', 'The first capital of the Bahmani Sultanate in the 14th century.', 'A major center for Sufi mysticism in the Deccan region.', 'Features the Jama Masjid, built accurately to resemble the mosque in Cordoba, Spain.', 'The Jama Masjid is entirely roofed, unlike most Indian mosques.'],
    ['Bijapur (Vijayapura)', 'Bijapur', 16.830, 75.714, 'Heritage', 'Free', 'Free', 'Oct-Feb', 'A city filled with monumental Islamic architecture from the Adil Shahi dynasty.', 'Established in the 10th-11th centuries by the Kalyani Chalukyas as Vijayapura.', 'Boasts some of the finest examples of Deccan architecture.', 'Characterized by bulbous domes, fine stucco work, and grand mausoleums.', 'Houses the largest medieval cannon in India, the Malik-e-Maidan.'],
    ['Davanagere', 'Davanagere', 14.464, 75.921, 'Heritage', 'Free', 'Free', 'Oct-Mar', 'The heart of Karnataka, globally famous for its butter dosa (Benne Dosa).', 'Originally an obscure village that grew rapidly under Tipu Sultan.', 'A pivotal center connecting North and South Karnataka cultures.', 'An agricultural and textile mill layout city.', 'Referred to as the "Manchester of Karnataka" due to its historic cotton mills.'],
    ['Shimoga (Shivamogga)', 'Shimoga', 13.929, 75.568, 'Nature', 'Free', 'Free', 'Oct-Mar', 'The gateway to the Western Ghats, surrounded by waterfalls and forests.', 'Historically the stronghold of the Keladi Nayakas in the 16th century.', 'Crucial agricultural hub heavily influenced by Malnad culture.', 'Lush green valleys, rivers, and Areca nut plantations.', 'The name purportedly translates to "Face of Lord Shiva".'],
    ['Yana Caves', 'Kumta', 14.587, 74.561, 'Nature', 'Free', 'Free', 'Oct-May', 'A spectacular geological formation featuring two massive black crystalline limestone outcrops.', 'According to mythology, the demon Bhasmasura was reduced to ashes here.', 'A popular trekking peak and Shivaratri pilgrimage site.', 'Towering 120-meter solid black karst rock structures amidst deep forests.', 'The two massive rocks are named Bhairaveshwara Shikhara and Mohini Shikhara.'],
    ['St. Mary\'s Island', 'Malpe', 13.379, 74.673, 'Nature', '₹300', '₹300', 'Oct-May', 'An island famous for its distinctive hexagonal columnar basaltic rock formations.', 'Vasco da Gama reportedly landed here in 1498 before reaching Calicut.', 'A unique geological monument recognized by the Geological Survey of India.', 'Hexagonal interlocking volcanic rock pillars dropping into the sea.', 'These rock formations were created by sub-aerial subvolcanic activity Madagascar was attached to India.'],
    ['Mandalpatti', 'Kodagu', 12.485, 75.715, 'Nature', 'Free', 'Free', 'Oct-Mar', 'A stunning viewpoint offering panoramic views of the Western Ghats in Coorg.', 'Has emerged recently as a premier off-roading destination.', 'A completely natural and uncommercialized viewpoint.', 'Rolling green shola grasslands devoid of heavy tree cover.', 'Requires a thrilling 4x4 Jeep ride through steep rocky paths.'],
    ['Z Point', 'Kemmanagundi', 13.541, 75.760, 'Adventure', 'Free', 'Free', 'Sep-Mar', 'A thrilling trekking trail leading to a steep, dramatic ridge line.', 'Part of the ancient royal hunting grounds of the Mysore Rajas.', 'Provides magnificent sunrise and sunset views over the valleys.', 'A natural, narrow cliff-side trail.', 'Trekking path passes through the beautiful Shanti Falls.'],
    ['Skandagiri', 'Chikkaballapur', 13.418, 77.683, 'Adventure', '₹250', '₹250', 'Nov-Mar', 'A historic hill fort famous for night trekking and walking above the clouds.', 'Fortified by Tipu Sultan as a strategic vantage point.', 'A prime adventure tourism spot near Bangalore.', 'Ruined stone fort walls interspersed with wild vegetation.', 'Trekkers typically start ascending at 2 AM to catch the sunrise piercing through the clouds.'],
    ['Kunti Betta', 'Pandavapura', 12.496, 76.680, 'Adventure', 'Free', 'Free', 'Oct-Mar', 'Two rocky hills associated with the Pandavas\' exile in the Mahabharata.', 'The Pandavas and their mother Kunti supposedly resided here during their exile.', 'A highly popular night trekking destination featuring a steep rock face.', 'Massive granite boulders and natural rock pillars.', 'The hill resembles a bowl, providing a natural fortress shape.'],
    ['Ramanagara', 'Ramanagara', 12.720, 77.281, 'Adventure', 'Free', 'Free', 'Oct-Feb', 'Famous for its massive boulders, silk market, and Ramadevara Betta.', 'A historic stronghold that changed hands between Nayakas, Mysore Kings, and the British.', 'The epicenter of India\'s silk industry and legendary rock-climbing spot.', 'Gigantic granite rock formations dotting the landscape.', 'The blockbuster Bollywood movie "Sholay" was filmed on these rocks.'],
    ['Savandurga', 'Magadi', 12.918, 77.293, 'Adventure', 'Free', 'Free', 'Sep-Mar', 'Considered the largest monolith hill in Asia, rising 1226 meters.', 'Served as the capital of the Hoysala Empire and later fortified by Kempe Gowda.', 'Revered by local rock climbers and pilgrims alike.', 'A sheer, massive bare granite dome.', 'Actually comprises two hills named Karigudda (black hill) and Biligudda (white hill).'],
    ['Honnemaradu', 'Shimoga', 14.153, 74.871, 'Adventure', 'Free', 'Free', 'Oct-Mar', 'A quaint village on the backwaters of the Sharavathi River.', 'Submerged by the construction of the Linganamakki Dam.', 'An eco-tourism hub focusing on trekking, kayaking, and camping.', 'Vast freshwater lake dotted with small green islands.', 'Means "Golden Lake" in the local Kannada dialect.'],
    ['Kavaledurga Fort', 'Shimoga', 13.725, 75.105, 'Heritage', 'Free', 'Free', 'Oct-Mar', 'A multi-tiered hill fort hidden deep within the Western Ghats jungle.', 'Built in the 9th century and heavily expanded by the Keladi Nayakas in the 16th century.', 'Represents a highly secluded royal fallback fortress.', 'Features three lines of walls, a ruined palace, and functional stepwells.', 'The fort relies on naturally defending steep drop-offs on three sides.'],
    ['Talakadu', 'Mysore', 12.190, 77.026, 'Spiritual', 'Free', 'Free', 'Oct-Mar', 'A desert-like town on the banks of the Kaveri, burying over 30 ancient temples.', 'Once a flourishing capital of the Western Gangas, later cursed by Queen Alamelamma.', 'A site of intense religious mystery where sand dunes constantly emerge.', 'Beautiful Hoysala and Ganga temples periodically excavated from the sand.', 'The "Curse of Talakadu" accurately predicted the town turning into sand.'],
    ['Kumara Parvatha', 'Dakshina Kannada', 12.673, 75.682, 'Adventure', '₹350', '₹350', 'Oct-Feb', 'The second highest peak in Kodagu, known as the toughest trek in Karnataka.', 'A revered mountain in Hindu mythology linked to Lord Kartikeya.', 'A rite of passage for serious trekkers in South India.', 'Steep grasslands giving way to rocky volcanic pinnacles.', 'The trek covers 28 kilometers round-trip through dense leeches and steep inclines.'],
    ['Banavasi', 'Uttara Kannada', 14.538, 75.011, 'Heritage', 'Free', 'Free', 'Oct-Mar', 'The oldest town in Karnataka, the capital of the ancient Kadamba dynasty.', 'Mentioned in the Mahabharata and works of Ashoka and Claudius Ptolemy (2nd century CE).', 'The birthplace of Kannada cultural identity and literature (Pampa).', 'Features the 9th-century Madhukeshwara temple with intricate stone cots.', 'Famous globally for its unique pineapples.']
  ].map(p => createPlace(p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],p[8],p[9],p[10],p[11],p[12]))
];

// Combine unique elements and avoid duplicates from existing database mentally
fs.writeFileSync(path.join(__dirname, '../data/karnatakaDestinationsRaw.js'), `module.exports = ${JSON.stringify(places, null, 4)};`, 'utf8');

console.log('Successfully generated ' + places.length + ' rich destination records into backend/data/karnatakaDestinationsRaw.js');
