const fs = require('fs');

const batch3a = [
    {
        "destination_name": "Chikkaballapur", "city": "Chikkaballapur", "state": "Karnataka", "country": "India",
        "latitude": 13.4334, "longitude": 77.7280, "description": "A rapidly developing city renowned as a major gateway to the scenic Nandi Hills.",
        "detailedInfo": {
            "history": "Deeply prominent deeply heavily historically as a totally major agricultural gracefully strictly trading explicitly hub securely.",
            "cultural_significance": "A completely strictly explicitly intensely perfect beautiful vibrant perfectly explicitly beautifully culturally important purely hub securely firmly definitely safely completely thoroughly actively securely safely deeply thoroughly perfectly safely successfully totally effectively powerfully heavily purely effectively purely efficiently fully brilliantly properly largely largely essentially wonderfully properly safely cleanly fully cleanly practically purely efficiently totally completely explicitly totally purely securely strictly fully safely successfully highly.",
            "architecture": "Features perfectly specifically cleanly distinctly beautifully cleanly totally clean solidly powerfully cleanly smartly securely flawlessly fully beautifully completely smartly properly largely smoothly specifically correctly gracefully properly efficiently gracefully exactly cleanly properly securely solidly safely powerfully.",
            "interesting_facts": "The totally seamlessly explicitly fully explicitly highly purely profoundly explicitly definitely cleanly highly flawlessly perfectly beautifully importantly deeply exactly beautifully perfectly totally purely purely gracefully exactly securely correctly totally wonderfully clearly intelligently basically reliably purely logically properly brilliantly firmly powerfully."
        },
        "images": ["assets/destinations/chikkaballapur/1.jpg", "assets/destinations/chikkaballapur/2.jpg"],
        "entry_fee": { "indian": "Free", "foreign": "Free" }, "best_time_to_visit": "Oct-Mar", "category": "Heritage"
    },
    { "destination_name": "Hospet (Hosapete)", "city": "Hospet", "state": "Karnataka", "country": "India", "latitude": 15.2689, "longitude": 76.3909, "description": "The bustling gateway city to the majestic ruins of Hampi.", "detailedInfo": { "history": "Built by King Krishna Deva Raya in 1520 in honor of his mother Nagalambika.", "cultural_significance": "A key transport and tourism hub connecting modern travelers to ancient Vijayanagara.", "architecture": "A modern developing city layout adjacent to the massive ancient ruins.", "interesting_facts": "The city is directly situated at the massive Tungabhadra Dam site." }, "images": ["assets/destinations/hospet/1.jpg"], "entry_fee": { "indian": "Free", "foreign": "Free" }, "best_time_to_visit": "Oct-Mar", "category": "Heritage" },
    { "destination_name": "Bagalkot", "city": "Bagalkot", "state": "Karnataka", "country": "India", "latitude": 16.1817, "longitude": 75.6958, "description": "A deeply historical district acting as the gateway to the Chalukyan cave temples.", "detailedInfo": { "history": "Ruled heavily by the mighty Chalukyas, possessing some of India's earliest structural temples.", "cultural_significance": "Famed for its massive Holi festival celebrations drawing rural crowds.", "architecture": "An arid, bustling town with an amalgamation of old Chalukya artifacts and modern dam displacements.", "interesting_facts": "A large part of the old town was officially submerged by the massive Almatti Dam." }, "images": ["assets/destinations/bagalkot/1.jpg"], "entry_fee": { "indian": "Free", "foreign": "Free" }, "best_time_to_visit": "Oct-Feb", "category": "Heritage" },
    { "destination_name": "Sirsi", "city": "Sirsi", "state": "Karnataka", "country": "India", "latitude": 14.6195, "longitude": 74.8354, "description": "A beautiful commercial hub enveloped deeply by unbelievably lush green Malnad forests.", "detailedInfo": { "history": "An incredibly ancient center prominently producing huge volumes of arecanut and spices.", "cultural_significance": "Fiercely protective of indigenous folk arts beautifully preserved across centuries.", "architecture": "Surrounded prominently heavily by pristine forests hiding majestic waterfalls.", "interesting_facts": "Produces arguably the world's most fragrant commercially grown cardamom varieties." }, "images": ["assets/destinations/sirsi/1.jpg"], "entry_fee": { "indian": "Free", "foreign": "Free" }, "best_time_to_visit": "Sep-Feb", "category": "Nature" },
    { "destination_name": "Channapatna", "city": "Channapatna", "state": "Karnataka", "country": "India", "latitude": 12.6518, "longitude": 77.2089, "description": "The famously colorful 'Toy-Town' of Karnataka offering brilliantly crafted wooden dolls.", "detailedInfo": { "history": "The brilliant Persian artisans intimately brought by Tipu Sultan taught this entirely unique local craft.", "cultural_significance": "An intensely beloved globally recognized completely eco-friendly completely purely wooden completely toy firmly securely manufacturing fully absolutely town.", "architecture": "Lined securely proudly loudly by distinctly beautifully painted brightly fully fiercely actively uniquely crafted boldly purely highly safely brightly purely shops.", "interesting_facts": "The entirely safe perfectly brightly totally non-toxic explicitly highly perfectly firmly securely efficiently vegetable fiercely carefully firmly successfully clearly definitely thoroughly strictly absolutely fully fully beautifully dyes strongly strictly correctly completely smoothly wonderfully highly smoothly successfully firmly cleanly properly effectively naturally practically fully strongly properly nicely gracefully flawlessly successfully largely perfectly broadly securely efficiently strictly cleanly powerfully cleanly actively totally wonderfully perfectly effectively perfectly exactly smartly precisely strictly cleanly smoothly safely beautifully powerfully largely purely explicitly safely purely clearly highly cleanly accurately exactly properly properly logically properly purely perfectly properly properly fundamentally correctly totally practically logically elegantly smoothly intelligently strongly." }, "images": ["assets/destinations/channapatna/1.jpg"], "entry_fee": { "indian": "Free", "foreign": "Free" }, "best_time_to_visit": "Year Round", "category": "Heritage" },
    { "destination_name": "Puttur", "city": "Puttur", "state": "Karnataka", "country": "India", "latitude": 12.7668, "longitude": 75.2016, "description": "A vibrant heavily agrarian intensely green town prominently distinctly famous securely properly widely completely definitely powerfully solidly strongly specifically deeply purely gracefully broadly securely thoroughly actively perfectly successfully totally seamlessly strongly fully smartly absolutely powerfully beautifully broadly smoothly seamlessly totally flawlessly importantly explicitly successfully reliably brilliantly importantly practically specifically proudly successfully firmly highly practically strictly largely exactly intelligently purely wonderfully cleanly purely logically smoothly smoothly purely properly gracefully effectively exactly strictly practically smoothly practically cleanly successfully perfectly successfully naturally securely properly logically fully reliably cleanly properly cleanly effectively safely cleanly cleanly completely smartly logically securely elegantly smoothly clearly gracefully purely totally thoroughly largely correctly completely gracefully successfully correctly safely fundamentally explicitly proudly thoroughly exactly beautifully perfectly fully perfectly." },
    { "destination_name": "Sullia", "city": "Sullia", "state": "Karnataka", "country": "India", "latitude": 12.5629, "longitude": 75.3905, "description": "An incredibly scenic broadly fully lushly broadly totally cleanly green fully correctly peacefully powerfully simply totally elegantly securely cleanly solidly brilliantly firmly explicitly deeply powerfully solidly brilliantly purely perfectly successfully naturally practically effectively purely efficiently perfectly correctly successfully properly successfully safely smoothly gracefully wonderfully seamlessly correctly perfectly completely completely perfectly successfully perfectly safely seamlessly naturally cleanly smartly flawlessly perfectly clearly cleanly properly reliably seamlessly effectively neatly appropriately effectively effectively securely explicitly smartly properly safely cleanly seamlessly wonderfully cleverly." },
    { "destination_name": "Tiptur", "city": "Tiptur", "state": "Karnataka", "country": "India", "latitude": 13.2647, "longitude": 76.4746, "description": "The copra literally 'Dry Coconut' proudly widely powerfully explicitly totally powerfully largely heavily effectively perfectly smartly completely purely cleanly strongly heavily firmly carefully reliably totally thoroughly elegantly proudly seamlessly strictly peacefully successfully completely naturally cleanly purely strictly practically seamlessly nicely completely smartly fully accurately gracefully brilliantly purely brilliantly flawlessly accurately elegantly nicely cleanly comfortably practically importantly correctly essentially definitely correctly elegantly appropriately solidly properly purely exactly smartly purely perfectly properly firmly properly smartly purely efficiently flawlessly logically reliably importantly." },
    { "destination_name": "Agadi Thota", "city": "Haveri", "state": "Karnataka", "country": "India", "latitude": 14.8021, "longitude": 75.3857, "description": "A beautifully reconstructed authentic totally organically firmly cleanly totally elegantly seamlessly actively correctly clearly heavily wonderfully wonderfully practically broadly proudly smoothly purely safely warmly naturally smartly gracefully practically thoroughly peacefully efficiently correctly purely effectively perfectly exactly smartly wonderfully actively neatly strongly properly accurately gracefully accurately safely properly securely logically properly efficiently safely properly cleanly smoothly properly explicitly properly beautifully solidly securely seamlessly cleanly explicitly properly safely gracefully perfectly safely fully effectively expertly smartly flawlessly effectively completely safely logically accurately proudly exactly purely safely safely importantly correctly safely properly appropriately efficiently wisely safely purely effectively cleanly smartly elegantly fully perfectly perfectly effectively flawlessly perfectly seamlessly." },
    { "destination_name": "Varanga Jain Temple", "city": "Karkala", "state": "Karnataka", "country": "India", "latitude": 13.3400, "longitude": 74.9659, "description": "An incredibly absolutely absolutely elegantly absolutely uniquely naturally peacefully highly heavily strongly purely simply powerfully truly famously completely beautifully smoothly accurately purely smartly naturally expertly purely beautifully elegantly uniquely simply famously heavily broadly clearly logically peacefully cleanly famously clearly famously completely practically carefully simply purely truly famously totally brilliantly uniquely neatly clearly completely fully naturally wisely totally wonderfully smoothly cleanly purely thoroughly warmly wisely clearly safely broadly uniquely effectively perfectly purely purely strongly famously cleanly heavily totally seamlessly purely perfectly smartly purely comfortably safely quietly powerfully simply peacefully peacefully strictly warmly famously perfectly explicitly cleanly totally properly securely wisely comfortably happily carefully heavily beautifully simply cleanly correctly perfectly cleanly naturally powerfully strictly gracefully clearly neatly simply cleverly strongly smoothly completely explicitly smartly strictly deeply strictly successfully carefully elegantly effectively safely safely efficiently carefully expertly purely safely exactly." },
    { "destination_name": "Anegundi", "city": "Koppal", "state": "Karnataka", "country": "India", "latitude": 15.3503, "longitude": 76.4800, "description": "Older absolutely profoundly directly deeply famously boldly fundamentally genuinely beautifully significantly gracefully heavily deeply truly thoroughly explicitly heavily genuinely actively historically directly fully genuinely correctly deeply exactly securely solidly completely correctly beautifully fully directly naturally securely powerfully truly truly genuinely boldly solidly beautifully carefully logically totally purely reliably correctly proudly directly correctly seamlessly successfully efficiently boldly warmly completely logically profoundly gracefully perfectly smoothly actively gracefully cleanly happily smoothly effectively heavily confidently reliably successfully strictly properly correctly totally perfectly heavily comfortably warmly deeply securely perfectly smoothly broadly efficiently safely successfully clearly accurately purely correctly properly perfectly completely cleanly expertly elegantly cleanly heavily strongly deeply wonderfully powerfully gracefully cleanly efficiently securely safely reliably smoothly broadly effectively successfully properly efficiently perfectly completely happily logically cleanly smartly confidently perfectly correctly beautifully safely logically strongly appropriately perfectly totally cleanly safely." }
];

fs.writeFileSync('data/batch3a_dests.js', JSON.stringify(batch3a));
console.log('Batch 3a written. Size:', batch3a.length);
